# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI testing

on:
  pull_request:
    branches: [ "master", "dev" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run: 
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
          miniforge-version: latest
          channels: conda-forge,bioconda
          channel-priority: true

    - name: install dependancies
      run: |
        wget https://raw.githubusercontent.com/jodyphelan/TBProfiler/dev/conda/linux-latest.txt
        conda create --name test --file linux-latest.txt
      
        
    - name: Install dependencies
      run: |
        conda activate test
        pip install --force-reinstall git+https://github.com/jodyphelan/pathogen-profiler.git@dev
        pip install --force-reinstall .
        pip install semver
    
    - name: list snpeff contents
      run: |
        snpEff databases > /dev/null
        ls -l /home/runner/miniconda3/envs/test/share/snpeff-5.2-1/
        ls -l /home/runner/miniconda3/envs/test/share/snpeff-5.2-1/data/
        ls -l /home/runner/miniconda3/envs/test/share/
        ls -l /home/runner/miniconda3/envs/test/share/snpeff-5.2-0/
        ls -l /home/runner/miniconda3/envs/test/share/snpeff-5.2-0/data/
        snpEff -version

    - name: Run tests
      run: |
        cd db
        python ../tb-profiler load_library tbdb
        cd ../tests
        mamba install pytest pandas importlib_resources -y
        pytest -x .
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
